version: '3.4'

services:
  flaskpythonlightningbackend:
    image: flaskpythonlightningbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      command: --quiet --logpath /dev/null 
#web:
#  environment:
#    - PYTHONUNBUFFERED=1